spring:
  application:
    name: eureka-client
server:
  port:8080
eureka:
  instance:
    hostname: 10.10.34.107
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://10.10.34.107:8888/eureka/