spring:
  application:
    name: topcloud-auth
  datasource:
    #    driverClassName: com.mysql.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.50.7:3306/gateway_zhoujun?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: jadp_csg
    password: jadp_csg
server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: 127.0.0.1:8081
  client:
    service-url:
      defaultZone: http://SuperAdmin:Ctp8899@127.0.0.1:8888/eureka
mybatis:
  mapper-locations: classpath*:com/comtop/topcloud/mapper/impl/*Mapper.xml
  type-aliases-package: com.comtop.topcloud.model