server:
  port: 8888
spring:
  application:
    name: eurka-server
#  security:
#    user:
#      name: admin
#      password: 123456
eureka:
  instance:
    hostname: 10.10.34.107
  client:
    registerWithEureka: false #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/